export const SET_CATEGORY="SET_CATEGORY";
export const ADD_CATEGORY="ADD_CATEGORY";
export const UPDATE_CATEGORY ="UPDATE_CATEGORY";
export const REMOVE_CATEGORY="REMOVE_CATEGORY";
export const RELOAD_CATEGORY ="RELOAD_CATEGORY";
